package com.aionos.agent.enums;

public enum ActionType {
    VERIFY_BOOKING,
    CHECK_FLIGHT_STATUS,
    CHECK_POLICY,
    INITIATE_REFUND,
    REBOOK_FLIGHT,
    ISSUE_MEAL_VOUCHER,
    ISSUE_LOUNGE_ACCESS,
    ARRANGE_HOTEL,
    PROCESS_INFORMATION_REQUEST,
    ESCALATE_TO_HUMAN
}
