package com.aionos.agent.enums;

public enum EscalationReason {
    EXCEEDS_COMPENSATION_POLICY,
    UNAUTHORIZED_UPGRADE,
    FARE_DIFFERENCE_EXCEEDS_LIMIT,
    LEGAL_THREAT_OR_FORMAL_COMPLAINT,
    NON_AIRLINE_CAUSED_EXCEPTION,
    DIFFERENT_REFUND_METHOD_REQUESTED,
    DATA_UNAVAILABLE,
    SUPERVISOR_APPROVAL_REQUIRED
}
